<?php 

/**
* Implements hook_block_info().
*/

function coins_entity_view($entity, $type, $view_mode, $langcode) {
    if ($view_mode == 'teaser' && $entity->type == 'coin') {
        $entity->content['field_coin']['#items'] = array_slice($entity->content['field_coin']['#items'], 0, 2);
    }
}

function coins_block_info() {
  $blocks = array();
  $blocks['Coins'] = array(
    'info' => t('Coins'),
  );

  return $blocks;
}

/**
* Implements hook_block_view().
*/
function coins_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'Coins':
      $block['subject'] = '';
      $block['content'] = _ca_block();
      break;
  }

  return $block;
}

function _ca_block() {
            $output = 'hi';

 
  return $output;
}